### ISSUE TITLE
Why not use Vue@3 + Vite to make project more faster and more readable

### ISSUE THREAD

**Issue by hermaproditus** [speculare-cloud/speculare-dashboard#15]
I found project use `mixins` to organize the component logic for reuse.

Why not use Vue@3 composition api to split logic in function, make it more clear and readable.

**Comment by Martichou** [comment]
Hey ! 

I've started the migration to Vue 3 [here](https://github.com/speculare-cloud/speculare-dashboard/tree/vue3-migration).
I will be a little bit busy and this will take some time. But if you would like to help, feel free to open a PR ! 🤙
